import json
import sys

treesitter_language_path = (sys.argv[1:]+["tree-sitter-civicc"])[0]

with open(treesitter_language_path + "/src/node-types.json") as f:
    lang = json.loads(f.read())

def subtypes(typ):
    for node in lang:
        if node["type"] == typ and node["named"] and "subtypes" in node:
            return sorted({n for subtyp in node["subtypes"] for n in subtypes(subtyp["type"])})
    return [typ]

def subtypes_kinds(typ):
    return "|".join(f'"{subtyp}"' for subtyp in subtypes(typ))

def kinds_match(typs, n="n"):
    if len(typs) == 1:
        return f'parse_{typs[0]['type'].replace("-","_")}({n}, bytes)'
    if len(n) > 3:
        return f"""let n2 = {n};
{kinds_match(typs, "n2")}"""
    return f"""match {n}.kind() {{
{"\n".join(f'        {subtypes_kinds(t["type"])} => todo!(parse_{t['type'].replace("-","_")}({n}, bytes)),' for t in typs)}
        _ => unreachable!(),
    }}"""
    return f"""match {n}.kind() {{
{"\n".join(f'        {subtypes_kinds(t["type"])} => todo!("parsing of {t['type']} within a {name} is not yet implemented", parse_{t['type'].replace("-","_")}({n}, bytes)),' for t in typs)}
        _ => unreachable!(),
    }}"""

def fields_parsers(fields):
    out = []
    needs_cursor = False
    for (name, f) in fields.items():
        rsname = name.replace("-", "_").replace(" ", "_")
        if f["multiple"]:
            out.append(f"""let {rsname}: Vec<_> = n.children_by_field_name("{name}", &mut cursor).map(|c|
        {kinds_match(f["types"], "c")}
    ).collect();""")
            needs_cursor = True
        elif f["required"]:
            out.append(f"""let {rsname} = {kinds_match(f["types"], f'n.child_by_field_name("{name}").unwrap()')};""")
        else:
            out.append(f"""let {rsname}: Option<_> = n.child_by_field_name("{name}").map(|c|
        {kinds_match(f["types"], "c")}
    );""")
    if needs_cursor:
        out = ["let mut cursor = n.walk();"] + out
    return "".join("\n    "+v for v in out)

print("""
use super::ast::*;
use tree_sitter::{Parser, Node};

fn node_to_string(n: Node, bytes: &[u8]) -> String {
    n.utf8_text(bytes).expect("Not UTF-8").to_string()
}

//Note: these autogenerated functions are a best effort boilerplate template
""".strip())

for node in lang:
    if node.get("extra",False) or not node["named"]:
        continue
    name = node["type"]
    rs_name = name.replace("-", "_")
    if "subtypes" in node:
        #supertype
        print(f"""
fn parse_{rs_name}(n: Node, bytes: &[u8]) -> ! {{
    {kinds_match(node["subtypes"])}
}}""")
    elif "fields" not in node:
        #token
        print(f"""
fn parse_{rs_name}(n: Node, bytes: &[u8]) -> ! {{
    let text = n.utf8_text(bytes).expect("Not UTF-8");
    todo!("parsing of the token {name} is not yet implemented")
}}""")
    elif "children" in node:
        if not node["children"]["multiple"]:
            #non supertype enum
            if node["children"]["required"]:
                unwrapper = "let n = n.child(0).unwrap();"
            else:
                unwrapper = f"""let Some(n) = n.child(0) else {{
        return todo!("parsing empty variant of {name} is not yet implemented");
    }};"""
            print(f"""
fn parse_{rs_name}(n: Node, bytes: &[u8]) -> ! {{{fields_parsers(node["fields"])}
    {unwrapper}
    {kinds_match(node["children"]["types"])}
}}""")
        elif (not node["fields"]) and (sum(1 for n in node["children"]["types"] if n["named"]) == 1):
            child_name = [n for n in node["children"]["types"] if n["named"]][0]["type"]
            child_rsname = child_name.replace("-", "_").replace(" ", "_")
            types = [{"type": child_name, "named": True}]
            if node["children"]["multiple"]:
                typ = "Vec<!>"
                body = f"""
    let mut cursor = n.walk();
    n.named_children(&mut cursor).filter(|c| !c.is_extra()).map(|c|
        {kinds_match(types, "c")}
    ).collect()"""
            elif node["children"]["required"]:
                typ = "!"
                body = f"""
    let mut cursor = n.walk();
    n.named_children(&mut cursor).filter(|c| !c.is_extra()).map(|c|
        {kinds_match(types, "c")}
    ).next().unwrap()"""
            else:
                typ = "Option<!>"
                body = f"""
    let mut cursor = n.walk();
    n.named_children(&mut cursor).filter(|c| !c.is_extra()).map(|c|
        {kinds_match(types, "c")}
    ).next()"""
            print(f"""
fn parse_{rs_name}(n: Node, bytes: &[u8]) -> {typ} {{{body}
}}""")
        else:
            print(f"""
fn parse_{rs_name}(n: Node, bytes: &[u8]) -> ! {{{fields_parsers(node["fields"])}
    //TODO: deal with children (or turn them into fields in your grammar)
    todo!("parsing on {name} is not yet implemented")
}}""")
    else:
        print(f"""
fn parse_{rs_name}(n: Node, bytes: &[u8]) -> ! {{{fields_parsers(node["fields"])}
    todo!("parsing on {name} is not yet implemented")
}}""")

print("""
pub fn parse(bytes: &[u8]) -> Option<!> {
    let mut parser = Parser::new();
    let lang = tree_sitter_civicc::LANGUAGE.into();
    parser.set_language(&lang).expect("Error loading grammar");
    let tree = parser.parse(bytes, None).unwrap();
    if coconut::parser::print_errors(&tree, bytes) {return None;}
    Some(parse_source_file(tree.root_node(), bytes))
}
""")
