use super::ast::*;
use tree_sitter::{Parser, Node};

fn node_to_string(n: Node, bytes: &[u8]) -> String {
    n.utf8_text(bytes).expect("Not UTF-8").to_string()
}

//Note: these autogenerated functions are a best effort boilerplate template

fn parse_expr(n: Node, bytes: &[u8]) -> Expr {
    match n.kind() {
        "constant" => Expr::Constant(parse_constant(n, bytes)),
        "dyop" => Expr::DyOp(parse_dyop(n, bytes)),
        "id" => Expr::Id(node_to_string(n, bytes)),
        _ => unreachable!(),
    }
}

fn parse_assign(n: Node, bytes: &[u8]) -> Assign {
    let expr = parse_expr(n.child_by_field_name("expr").unwrap(), bytes);
    let varlet = node_to_string(n.child_by_field_name("varlet").unwrap(), bytes);
    Assign{varlet, expr}
}

fn parse_constant(n: Node, bytes: &[u8]) -> Constant {
    let n = n.child(0).unwrap();
    let text = n.utf8_text(bytes).expect("Not UTF-8");
    match n.kind() {
        "boolval" => Constant::Bool(text == "true"),
        "floatval" => Constant::Float(text.parse().unwrap()),
        "intval" => Constant::Num(text.parse().unwrap()),
        _ => unreachable!(),
    }
}

fn parse_dyop(n: Node, bytes: &[u8]) -> DyOp {
    let left = parse_expr(n.child_by_field_name("left").unwrap(), bytes);
    let op = parse_dyoptype(n.child_by_field_name("op").unwrap(), bytes);
    let right = parse_expr(n.child_by_field_name("right").unwrap(), bytes);
    DyOp{left: Box::new(left), op, right: Box::new(right)}
}

fn parse_source_file(n: Node, bytes: &[u8]) -> Program {
    let mut cursor = n.walk();
    Program(n.named_children(&mut cursor).filter(|c| !c.is_extra()).map(|c|
        parse_assign(c, bytes)
    ).collect())
}

fn parse_dyoptype(n: Node, bytes: &[u8]) -> DyOpType {
    let text = n.utf8_text(bytes).expect("Not UTF-8");
    match text {
        "+" => DyOpType::Add,
        "-" => DyOpType::Sub,
        "*" => DyOpType::Mul,
        "/" => DyOpType::Div,
        "%" => DyOpType::Mod,
        "<" => DyOpType::Lt,
        "<=" => DyOpType::Le,
        ">" => DyOpType::Gt,
        ">=" => DyOpType::Ge,
        "==" => DyOpType::Eq,
        "!=" => DyOpType::Ne,
        "&&" => DyOpType::And,
        "||" => DyOpType::Or,
        _ => unreachable!(),
    }
}

pub fn parse(bytes: &[u8]) -> Option<Program> {
    let mut parser = Parser::new();
    let lang = tree_sitter_civicc::LANGUAGE.into();
    parser.set_language(&lang).expect("Error loading grammar");
    let tree = parser.parse(bytes, None).unwrap();
    if print_errors(&tree, bytes) {return None;}
    Some(parse_source_file(tree.root_node(), bytes))
}

fn print_errors(tree: &tree_sitter::Tree, bytes: &[u8]) -> bool {
    let mut has_errors = false;
    let mut cursor = tree.walk();
    loop {
        let node = cursor.node();

        if node.is_error() || node.is_missing() {
            eprintln!("Syntax error at {}:{}", node.start_position().row + 1, node.start_position().column + 1);
            eprintln!("Problematic code: {}", str::from_utf8(&bytes[node.byte_range()]).expect("Invalit UTF-8"));
            has_errors = true;
        }

        if cursor.goto_first_child() {continue;}
        if cursor.goto_next_sibling() {continue;}

        loop {
            if !cursor.goto_parent() {return has_errors;}
            if cursor.goto_next_sibling() {break;}
        }
    }
}
